DROP DATABASE IF EXISTS triviadb_test;
DROP USER IF EXISTS caryn1;
CREATE DATABASE triviadb_test;
CREATE USER caryn1 WITH ENCRYPTED PASSWORD 'student';
GRANT ALL PRIVILEGES ON DATABASE triviadb_test TO caryn1;
ALTER USER caryn1 CREATEDB;
ALTER USER caryn1 WITH SUPERUSER;